import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:tien_day/data/dev/excel_chi_tieu_map.dart';

import 'read_chitieu_xlsx.dart';

/// One-time development seed helper. Not a user-facing Import feature.
///
/// dart run tool/seed_transactions_from_excel.dart --xlsx PATH
/// flutter run -t tool/seed_on_device.dart
Future<void> main(List<String> args) async {
  String? xlsxPath;
  for (var i = 0; i < args.length; i++) {
    final arg = args[i];
    if (arg == '--xlsx' && i + 1 < args.length) {
      xlsxPath = args[++i];
    } else if (arg == '--help' || arg == '-h') {
      stdout.writeln(_usage);
      return;
    }
  }

  xlsxPath ??= _defaultXlsxPath();
  if (xlsxPath == null || !File(xlsxPath).existsSync()) {
    stderr.writeln(
      'Excel file not found. Pass --xlsx /path/to/Template_Chi_Tieu_Toi_Gian.xlsx',
    );
    exitCode = 64;
    return;
  }

  final rows = readChiTieuFile(xlsxPath);
  final dataRows = rows.where((row) => !row.isEmpty).toList(growable: false);
  var mapped = 0;
  var skippedInvalid = 0;
  final invalidRows = <SeedRowFailure>[];
  final seen = <String>{};
  var skippedDuplicate = 0;
  for (final row in dataRows) {
    final result = mapChiTieuRow(row);
    if (result.invalid != null) {
      skippedInvalid += 1;
      invalidRows.add(result.invalid!);
      continue;
    }
    final item = result.mapped!;
    if (!seen.add(item.fingerprint)) {
      skippedDuplicate += 1;
      continue;
    }
    mapped += 1;
  }

  final payloadFile = File(
    p.join(p.dirname(Platform.script.toFilePath()), 'seed_payload.local.g.dart'),
  );
  payloadFile.writeAsStringSync(_payloadSource(rows));

  stdout.writeln('Excel rows found: ${dataRows.length}');
  stdout.writeln();
  stdout.writeln('Imported: 0');
  stdout.writeln('Ready to insert: $mapped');
  stdout.writeln('Skipped duplicate: $skippedDuplicate');
  stdout.writeln('Skipped invalid: $skippedInvalid');
  stdout.writeln('Failed: 0');
  stdout.writeln();
  stdout.writeln('Wrote ${payloadFile.path}');
  stdout.writeln('Insert into the app database with:');
  stdout.writeln('  flutter run -t tool/seed_on_device.dart');
  for (final row in invalidRows) {
    stdout.writeln();
    stdout.writeln('Row ${row.excelRowNumber}');
    stdout.writeln('Reason: ${row.reason}');
  }
}

String? _defaultXlsxPath() {
  final toolDir = p.dirname(Platform.script.toFilePath());
  final inRepo = p.normalize(
    p.join(toolDir, '../../scripts/Template_Chi_Tieu_Toi_Gian.xlsx'),
  );
  if (File(inRepo).existsSync()) return inRepo;
  final home = Platform.environment['HOME'];
  if (home == null) return inRepo;
  final downloads = p.join(home, 'Downloads', 'Template_Chi_Tieu_Toi_Gian.xlsx');
  if (File(downloads).existsSync()) return downloads;
  return inRepo;
}

String _payloadSource(List<ExcelChiTieuRow> rows) {
  final data = [
    for (final row in rows)
      if (!row.isEmpty)
        {
          'excelRowNumber': row.excelRowNumber,
          'ngay': _jsonValue(row.ngay),
          'nhom': _jsonValue(row.nhom),
          'doiTuong': _jsonValue(row.doiTuong),
          'khoanChi': _jsonValue(row.khoanChi),
          'soTien': _jsonValue(row.soTien),
          'thanhToan': _jsonValue(row.thanhToan),
          'ghiChu': _jsonValue(row.ghiChu),
          'tag': _jsonValue(row.tag),
        },
  ];
  final json = const JsonEncoder.withIndent('  ').convert(data);
  return '''
// Generated by seed_transactions_from_excel.dart. Development only.
const seedPayloadJson = r\'\'\'$json\'\'\';
''';
}

Object? _jsonValue(Object? value) {
  if (value == null) return null;
  if (value is DateTime) return value.toIso8601String();
  if (value is num || value is bool) return value;
  return value.toString();
}

const _usage = '''
One-time development seed from sheet ChiTieu.

  dart run tool/seed_transactions_from_excel.dart --xlsx FILE
  flutter run -t tool/seed_on_device.dart

Does not reset the database. Re-runs skip duplicates.
This is not a user-facing Import feature.
''';
